# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 22:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modsec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
