# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modsec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
