# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modsec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
