# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modsec', '0002_auto_20171112_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cont',
            field=models.IntegerField(default=0),
        ),
    ]
